name: Trigger Sync

on:
  pull_request:
    types: [closed]
    branches:
      - 'pbna/**'
      - 'pog/**'
      - 'combined/**'

jobs:
  call-downsync:
    if: github.event.pull_request.merged == true

    uses: freelancenaveenkumar-ops/reusable_github_actions/.github/workflows/downsync.yaml@dynamic_downsync_workflow

    with:
      source_branch: ${{ github.event.pull_request.base.ref }}

    secrets:
      API_TOKEN: ${{ secrets.DYNAMIC_SYNC_TOKEN }}
