name: Dynamic Branch Sync on PR Merge

on:
  pull_request:
    types:
      - closed   # fires when PR is closed (merged or not)
    branches:
      - 'pbna/5.1'
      - 'pbna/5.2'
      - 'pog/5.1'
      - 'pog/5.2' # listen to all branches

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read branch flow
        id: branch_flow
        run: |
          BRANCH="${GITHUB_REF##*/}"
          echo "Source branch: $BRANCH"

          FLOW=$(jq -r --arg b "$BRANCH" '.[$b] | @csv' .github/sync-flow.json)
          echo "Flow: $FLOW"
          echo "flow=$FLOW" >> $GITHUB_OUTPUT

      - name: Trigger PRs
        if: ${{ steps.branch_flow.outputs.flow != '' }}
        run: |
          SRC="${GITHUB_REF##*/}"
          IFS=',' read -ra TARGETS <<< "${{ steps.branch_flow.outputs.flow }}"

          for DEST in "${TARGETS[@]}"; do
            echo "Creating PR: $SRC → $DEST"
          done
        #env:
          #GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
