name: Call Reusable Workflow

# on:
on:
  pull_request:
    types: [closed]
    branches:
      - 'pbna/**'
      - 'pog/**'
      - 'combined/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  call-workflow:
    uses: freelancenaveenkumar-ops/reusable_github_actions/.github/workflows/test-called.yaml@main

    with:
      message: "Hello from calling repository"
    secrets: inherit
