name: Call Reusable Workflow

on:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: freelancenaveenkumar-ops/reusable_github_actions/.github/workflows/test-called.yaml@main

    with:
      message: "Hello from calling repository"
