name: Call Reusable Workflow

# on:
#   workflow_dispatch:
on:
  pull_request:
    types: [closed]
    branches:
      - 'pbna/**'
      - 'pog/**'
      - 'combined/**'

jobs:
  call-workflow:
    uses: freelancenaveenkumar-ops/reusable_github_actions/.github/workflows/test-called.yml@main

    with:
      message: "Hello from calling repository"
